name: Deploy FamilyTree 3.0

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Placeholder
        run: echo "Deployment handled via cPanel Git"